#!/usr/bin/env sh
. ./scripts/test/setup

nom init
nom add gulasch $EX_DIR/gulasch.yml

touch $NOM_DIR/foobar
nom add foobar $EX_DIR/gulasch.yml
nom --force add foobar $EX_DIR/gulasch.yml

for recipe in `ls $EX_DIR/*.yml`; do
    basename=${recipe##*/}
    basename=${basename%.yml}
    nom add $basename $recipe
done

nom add aelgsons_versuchung2 $EX_DIR/aelgsons_versuchung.yml --image $EX_DIR/images/auberginen_2.jpg --image $EX_DIR/images/auberginen_3.jpg
nom --quiet add recipe_dummy1
nom --quiet add sidedish/recipe_dummy2
nom add gulasch --image $EX_DIR/images/SIhiZHf.jpg
nom add gulasch --image $EX_DIR/images/SIhiZHf.jpg
