#!/usr/bin/env sh
. ./scripts/test/setup
. ./scripts/test/setup_hgy

hgy grocery --persons 1 filet_wellington.yml
hgy grocery --persons 2 filet_wellington.yml
hgy grocery --persons 3 filet_wellington.yml
hgy grocery --persons 4 filet_wellington.yml
hgy grocery --persons 5 filet_wellington.yml
hgy grocery --persons 10 filet_wellington.yml
hgy grocery --persons 20 filet_wellington.yml
