#!/usr/bin/env sh
. ./scripts/test/setup
. ./scripts/test/setup_hgy

hgy grocery --persons 1 filet_wellington
hgy grocery --persons 2 filet_wellington
hgy grocery --persons 10 filet_wellington

hgy plan > $HGY_DIR/plan1
hgy plan > $HGY_DIR/plan2

hgy grocery --persons 4 --plan $HGY_DIR/plan1
hgy grocery --persons 2 --plan $HGY_DIR/plan1 --plan $HGY_DIR/plan2

hgy grocery --persons 1 schwaebischer_kartoffelsalat
hgy grocery --persons 10 schwaebischer_kartoffelsalat
