#!/usr/bin/env sh
. ./scripts/test/setup
. ./scripts/test/setup_nom

nom grocery --persons 1 filet_wellington
nom grocery --persons 2 filet_wellington
nom grocery --persons 10 filet_wellington

nom plan > $NOM_DIR/plan1
nom plan > $NOM_DIR/plan2

nom grocery --persons 4 --plan $NOM_DIR/plan1
nom grocery --persons 2 --plan $NOM_DIR/plan1 --plan $NOM_DIR/plan2

nom grocery --persons 1 schwaebischer_kartoffelsalat
nom grocery --persons 10 schwaebischer_kartoffelsalat
