#!/usr/bin/env sh
. ./scripts/test/setup

hgy init
for recipe in `ls /tmp/examples/*.yml`; do
    hgy add `basename $recipe` $recipe
done
hgy serve --static /tmp/hgy/html
xdg-open /tmp/hgy/html/index.html
